import fs from 'node:fs/promises';
import path from 'node:path';
import * as cheerio from 'cheerio';

const symbol = (process.argv[2] || '005930').replace(/[^0-9]/g, '');
const url = `https://comp.fnguide.com/SVO2/ASP/SVD_Finance.asp?pGB=1&gicode=A${symbol}`;

function toNumber(text) {
  if (!text) return null;
  const cleaned = text.replace(/,/g, '').replace(/\([^)]*\)/g, '').trim();
  if (!cleaned || cleaned === '-') return null;
  const value = Number(cleaned);
  return Number.isFinite(value) ? value : null;
}

function findMetricRow(table, candidates) {
  return table.find((row) => candidates.some((candidate) => row[0]?.includes(candidate)));
}

function buildRows(headers, table) {
  const revenue = findMetricRow(table, ['매출액']);
  const operatingProfit = findMetricRow(table, ['영업이익']);
  const netIncome = findMetricRow(table, ['당기순이익', '지배주주순이익']);
  const eps = findMetricRow(table, ['EPS']);
  const fcf = findMetricRow(table, ['FCF']);
  const roe = findMetricRow(table, ['ROE']);
  const debtRatio = findMetricRow(table, ['부채비율']);
  const currentRatio = findMetricRow(table, ['유동비율']);

  return headers.map((period, idx) => ({
    period,
    revenue: toNumber(revenue?.[idx + 1]),
    operatingProfit: toNumber(operatingProfit?.[idx + 1]),
    netIncome: toNumber(netIncome?.[idx + 1]),
    eps: toNumber(eps?.[idx + 1]),
    fcf: toNumber(fcf?.[idx + 1]),
    roe: toNumber(roe?.[idx + 1]),
    debtRatio: toNumber(debtRatio?.[idx + 1]),
    currentRatio: toNumber(currentRatio?.[idx + 1]),
  }));
}

const res = await fetch(url, {
  headers: {
    'User-Agent': 'Mozilla/5.0',
    Referer: 'https://comp.fnguide.com/',
  },
});

if (!res.ok) {
  throw new Error(`FnGuide fetch failed: ${res.status}`);
}

const html = await res.text();
const $ = cheerio.load(html);
const companyName = $('.corp_group1 h1').first().text().trim() || symbol;
const tables = $('table').toArray().slice(0, 8);

const parsedTables = tables.map((table) => {
  const rows = [];
  $(table).find('tr').each((_, tr) => {
    const cells = $(tr).find('th,td').map((__, cell) => $(cell).text().replace(/\s+/g, ' ').trim()).get();
    if (cells.length) rows.push(cells);
  });
  return rows;
});

const annualTable = parsedTables.find((table) => table.some((r) => r.join(' ').includes('매출액')) && table.some((r) => r.join(' ').includes('/12')));
const quarterlyTable = parsedTables.find((table) => table.some((r) => r.join(' ').includes('매출액')) && table.some((r) => r.join(' ').includes('/03')));

if (!annualTable || !quarterlyTable) {
  throw new Error('FnGuide table parsing failed. HTML structure may have changed.');
}

const annualHeaders = annualTable[0].slice(1, 6);
const quarterlyHeaders = quarterlyTable[0].slice(1, 9);

const payload = {
  symbol,
  companyName,
  annual: buildRows(annualHeaders, annualTable),
  quarterly: buildRows(quarterlyHeaders, quarterlyTable),
  meta: {
    source: 'FnGuide scrape script',
    updatedAt: new Date().toISOString(),
    note: 'Generated by scripts/fetch-fnguide.mjs',
  },
};

const filePath = path.join(process.cwd(), 'public', 'data', 'financials', `${symbol}.json`);
await fs.writeFile(filePath, JSON.stringify(payload, null, 2), 'utf-8');
console.log(`Saved ${filePath}`);
